trigger:

- main



pool:

  vmImage: 'windows-latest'



steps:

- task: UseDotNet@2

  inputs:

    packageType: 'sdk'

    version: '8.0.x'

    installationPath: $(Agent.ToolsDirectory)/dotnet



- task: DotNetCoreCLI@2

  inputs:

    command: 'restore'

    projects: 'EduSyncBackend/EduSyncBackend/EduSyncBackend.csproj'



- task: DotNetCoreCLI@2

  inputs:

    command: 'build'

    projects: 'EduSyncBackend/EduSyncBackend/EduSyncBackend.csproj'

    arguments: '--configuration Release'



- task: DotNetCoreCLI@2

  inputs:

    command: 'publish'

    publishWebProjects: true

    projects: 'EduSyncBackend/EduSyncBackend/EduSyncBackend.csproj'

    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'

    zipAfterPublish: true



- task: ProjectBackend

  inputs:

    azureSubscription: 'MyAzureConnection'

    appType: 'webApp'

    appName: 'edusync-backend-brijesh'

    package: '$(Build.ArtifactStagingDirectory)//*.zip'
